### ISSUE TITLE
Declare dependency on numpy

### ISSUE THREAD

**Issue by hajapy** [v7labs/upolygon#5]
This library [depends on numpy](https://github.com/v7labs/upolygon/blob/master/upolygon/find_contours.pyx#L4), but the [setup.py install_requires is empty.](https://github.com/v7labs/upolygon/blob/2bd6133be5be242b03eb004b23694ea3e309debe/setup.py#L32)

**Comment by simedw** [comment]
Hi @hajapy, this has been resolved in master.
